### ISSUE TITLE
4 check

### ISSUE THREAD

**Issue by nhatnguyen233** [frzleaf/novice#2]
#include<stdio.h>
#include<conio.h>

int main()
{
    int a[10]= {1, 5, 6, 1, 3, 4, 9, 6, 10, 2};
    int d=1,k=0;
    while (k<10){
        printf("Day %d: %d ",d,a[k]);
        for (;k<9;k++) {
            if (a[k]<=a[k+1])
                printf("%d ",a[k+1]);
            else break;
        }
        printf("\n");
        k++;
        d++;
    }
        return 0;
}

**Comment by frzleaf** [comment]
đù má, đây là tạo issue, không phải pull request
